// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.MsSql.DesignTime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for Microsoft SQL Server database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.4")>]
[<assembly: AssemblyFileVersionAttribute("1.5.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.MsSql.DesignTime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for Microsoft SQL Server database access."
    let [<Literal>] AssemblyVersion = "1.5.4"
    let [<Literal>] AssemblyFileVersion = "1.5.4"
