// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.DuckDb.Runtime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for DuckDb database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.14")>]
[<assembly: AssemblyFileVersionAttribute("1.5.14")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.DuckDb.Runtime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for DuckDb database access."
    let [<Literal>] AssemblyVersion = "1.5.14"
    let [<Literal>] AssemblyFileVersion = "1.5.14"
