// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.Odbc.Runtime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for any ODBC connection database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.6")>]
[<assembly: AssemblyFileVersionAttribute("1.5.6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.Odbc.Runtime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for any ODBC connection database access."
    let [<Literal>] AssemblyVersion = "1.5.6"
    let [<Literal>] AssemblyFileVersion = "1.5.6"
