--SET foreign_key_checks = 0;
--DROP TABLE `hr`.`countries`, `hr`.`departments`, `hr`.`employees`, `hr`.`job_history`, `hr`.`jobs`, `hr`.`locations`, `hr`.`regions`;
--SET foreign_key_checks = 1;

CREATE TABLE COUNTRIES
(	
	COUNTRY_ID CHAR(2) NOT NULL, 
	COUNTRY_NAME VARCHAR(40), 
	REGION_ID INT, 
	OTHER blob SUB_TYPE 1, 
	PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE LOCATIONS 
(	
	LOCATION_ID INT NOT NULL,
    PRIMARY KEY (LOCATION_ID), 
	STREET_ADDRESS VARCHAR(40), 
	POSTAL_CODE VARCHAR(12), 
	CITY VARCHAR(30) NOT NULL, 
	STATE_PROVINCE VARCHAR(25), 
	COUNTRY_ID CHAR(2)

);


CREATE TABLE REGIONS
(	
	REGION_ID INT NOT NULL, 
	REGION_NAME VARCHAR(25), 
	REGION_DESCRIPTION BLOB SUB_TYPE 1, 
    PRIMARY KEY (REGION_ID)
);


CREATE TABLE DEPARTMENTS
(	
	 DEPARTMENT_ID INT, 
	 DEPARTMENT_NAME VARCHAR(30) NOT NULL, 
	 MANAGER_ID INT, 
	 LOCATION_ID INT, 
	 PRIMARY KEY (DEPARTMENT_ID)

);


CREATE TABLE JOBS
(	
	 JOB_ID VARCHAR(10),
     PRIMARY KEY (JOB_ID), 
	 JOB_TITLE VARCHAR(35) NOT NULL, 
	 MIN_SALARY NUMERIC(15,4), 
	 MAX_SALARY NUMERIC(15,4)
	 
);


CREATE TABLE EMPLOYEES
(	
    EMPLOYEE_ID INT, 
	FIRST_NAME VARCHAR(20), 
	LAST_NAME VARCHAR(25) NOT NULL, 
	EMAIL VARCHAR(25) NOT NULL, 
	PHONE_NUMBER VARCHAR(20), 
	HIRE_DATE DATE NOT NULL, 
	JOB_ID VARCHAR(10) NOT NULL, 
	SALARY NUMERIC(15,4), 
	COMMISSION_PCT NUMERIC(15,4), 
	MANAGER_ID INT, 
	DEPARTMENT_ID INT, 
	CHECK (SALARY > 0), 
	UNIQUE (EMAIL), 
	PRIMARY KEY (EMPLOYEE_ID)
);

COMMENT ON TABLE EMPLOYEES IS 'Employees is a very important table, used in many places.';
COMMENT ON COLUMN EMPLOYEES.EMAIL IS 'Email is a max-25-char item, having at-sign and a dot';

CREATE TABLE JOB_HISTORY 
(	
	EMPLOYEE_ID int NOT NULL, 
	START_DATE DATE NOT NULL, 
	END_DATE DATE NOT NULL, 
	JOB_ID VARCHAR(10) NOT NULL, 
	DEPARTMENT_ID int,
	CHECK (end_date > start_date), 
	PRIMARY KEY (EMPLOYEE_ID, START_DATE)

);
