// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.PostgreSql.DesignTime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for PostgreSql database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.9")>]
[<assembly: AssemblyFileVersionAttribute("1.5.9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.PostgreSql.DesignTime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for PostgreSql database access."
    let [<Literal>] AssemblyVersion = "1.5.9"
    let [<Literal>] AssemblyFileVersion = "1.5.9"
