// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.SQLite.DesignTime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQLite database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.17")>]
[<assembly: AssemblyFileVersionAttribute("1.5.17")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.SQLite.DesignTime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for SQLite database access."
    let [<Literal>] AssemblyVersion = "1.5.17"
    let [<Literal>] AssemblyFileVersion = "1.5.17"
