// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.Common")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type provider for SQL database access, common library")>]
[<assembly: AssemblyVersionAttribute("1.5.12")>]
[<assembly: AssemblyFileVersionAttribute("1.5.12")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.Common"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type provider for SQL database access, common library"
    let [<Literal>] AssemblyVersion = "1.5.12"
    let [<Literal>] AssemblyFileVersion = "1.5.12"
