// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.FireBird.DesignTime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for FireBird database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.3")>]
[<assembly: AssemblyFileVersionAttribute("1.5.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.FireBird.DesignTime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for FireBird database access."
    let [<Literal>] AssemblyVersion = "1.5.3"
    let [<Literal>] AssemblyFileVersion = "1.5.3"
