// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.Oracle.Runtime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for Oracle database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.0")>]
[<assembly: AssemblyFileVersionAttribute("1.5.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.Oracle.Runtime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for Oracle database access."
    let [<Literal>] AssemblyVersion = "1.5.0"
    let [<Literal>] AssemblyFileVersion = "1.5.0"
