// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.Odbc.DesignTime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for any ODBC connection database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.9")>]
[<assembly: AssemblyFileVersionAttribute("1.5.9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.Odbc.DesignTime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for any ODBC connection database access."
    let [<Literal>] AssemblyVersion = "1.5.9"
    let [<Literal>] AssemblyFileVersion = "1.5.9"
