// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.MySql.DesignTime")>]
[<assembly: AssemblyProductAttribute("SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for MySQL database and MariaDB database access.")>]
[<assembly: AssemblyVersionAttribute("1.5.16")>]
[<assembly: AssemblyFileVersionAttribute("1.5.16")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.MySql.DesignTime"
    let [<Literal>] AssemblyProduct = "SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for MySQL database and MariaDB database access."
    let [<Literal>] AssemblyVersion = "1.5.16"
    let [<Literal>] AssemblyFileVersion = "1.5.16"
