CREATE USER hr
  IDENTIFIED BY password
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION
  , CREATE SEQUENCE
  , CREATE TABLE
  , CREATE VIEW
  , CREATE MATERIALIZED VIEW
  , CREATE PROCEDURE
  , CREATE TRIGGER
  TO hr;
