connect hr/password;

ALTER TABLE "COUNTRIES" ADD CONSTRAINT "COUNTR_REG_FK"
  FOREIGN KEY ("REGION_ID")
  REFERENCES "REGIONS" ("REGION_ID")
  ENABLE;

ALTER TABLE "DEPARTMENTS" ADD CONSTRAINT "DEPT_LOC_FK"
  FOREIGN KEY ("LOCATION_ID")
  REFERENCES "LOCATIONS" ("LOCATION_ID")
  ENABLE;

ALTER TABLE "DEPARTMENTS" ADD CONSTRAINT "DEPT_MGR_FK"
  FOREIGN KEY ("MANAGER_ID")
  REFERENCES "EMPLOYEES" ("EMPLOYEE_ID")
  ENABLE;

ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMP_DEPT_FK"
  FOREIGN KEY ("DEPARTMENT_ID")
  REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID")
  ENABLE;

ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMP_JOB_FK"
  FOREIGN KEY ("JOB_ID")
  REFERENCES "JOBS" ("JOB_ID")
  ENABLE;

ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMP_MANAGER_FK"
  FOREIGN KEY ("MANAGER_ID")
  REFERENCES "EMPLOYEES" ("EMPLOYEE_ID")
  ENABLE;

ALTER TABLE "JOB_HISTORY" ADD CONSTRAINT "JHIST_DEPT_FK"
  FOREIGN KEY ("DEPARTMENT_ID")
  REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID")
  ENABLE;

ALTER TABLE "JOB_HISTORY" ADD CONSTRAINT "JHIST_EMP_FK"
  FOREIGN KEY ("EMPLOYEE_ID")
  REFERENCES "EMPLOYEES" ("EMPLOYEE_ID")
  ENABLE;

ALTER TABLE "JOB_HISTORY" ADD CONSTRAINT "JHIST_JOB_FK"
  FOREIGN KEY ("JOB_ID")
  REFERENCES "JOBS" ("JOB_ID")
  ENABLE;

ALTER TABLE "LOCATIONS" ADD CONSTRAINT "LOC_C_ID_FK"
  FOREIGN KEY ("COUNTRY_ID")
  REFERENCES "COUNTRIES" ("COUNTRY_ID")
  ENABLE;

COMMIT;
